module.exports = {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  transform: {
    '^.+\\.(ts)$': ['ts-jest', { useESM: true, tsconfig: '<rootDir>/tsconfig.json' }],
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: ['**/*.spec.ts'],
  roots: ['<rootDir>/src/tests', '<rootDir>/tests'],
  moduleNameMapper: {
    '^@sperm-odyssey/shared$': '<rootDir>/../shared/src/index.ts',
    '^@sperm-odyssey/shared/(.*)$': '<rootDir>/../shared/src/$1',
    '^\.\./src/sim/(.*)\.js$': '<rootDir>/src/sim/$1.ts',
    '^\.\./\.\./src/sim/(.*)\.js$': '<rootDir>/src/sim/$1.ts',
    '^\.\./sim/(.*)\.js$': '<rootDir>/src/sim/$1.ts',
    '^\./Biology\.js$': '<rootDir>/src/sim/Biology.ts',
    '^\./BiologyRules\.js$': '<rootDir>/src/sim/BiologyRules.ts',
    '^\./World\.js$': '<rootDir>/src/sim/World.ts',
    '^\./RNG\.js$': '<rootDir>/src/sim/RNG.ts',
    '^\./Physics\.js$': '<rootDir>/src/sim/Physics.ts',
    '^\.\./shared/src/(.*)\.js$': '<rootDir>/../shared/src/$1.ts',
    '^\.\./\.\./src/replay/(.*)\.js$': '<rootDir>/src/replay/$1.ts',
    '^\.\./src/replay/(.*)\.js$': '<rootDir>/src/replay/$1.ts',
    '^\.\./replay/(.*)\.js$': '<rootDir>/src/replay/$1.ts',
    '^\.\./util/(.*)\.js$': '<rootDir>/src/util/$1.ts',
    '^\.\./src/(.*)\.js$': '<rootDir>/src/$1.ts',
    '^\.\/constants\.js$': '<rootDir>/../shared/src/constants.ts',
    '^\.\/schema\.js$': '<rootDir>/../shared/src/schema.ts',
    '^\.\/types\.js$': '<rootDir>/../shared/src/types.ts',
    '^\.\/rng\.js$': '<rootDir>/../shared/src/rng.ts',
    '^\.\/replay\.js$': '<rootDir>/../shared/src/replay.ts',
    '^\.\/rating\.js$': '<rootDir>/../shared/src/rating.ts',
  },
};
